# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_game_play_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='vote',
            field=models.CharField(choices=[('Excellent', 'Molto bello'), ('Good', 'Buono'), ('Normal', 'Normale'), ('Bad', 'Brutto'), ('Horrible', 'Schifo')], default='Normale', max_length=20),
        ),
    ]
